project:
  type: book
  output-dir: docs

book:
  title: "言語統計処理a"
  author: "寺井雅人 (Terai Masato)"
  date: "2026/3/23"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt



