# はじめに {.unnumbered}

::: {.callout-warning}
この資料を作成者に無断で配布することは厳禁です。
:::

## 担当者
- 寺井雅人
  - 所属：名古屋学院大学　外国語学部
  - Website: （[googlesite](https://sites.google.com/view/masatoterai/)）
    - より詳しい情報はWebsiteをご覧ください。

## 講義概要
　この資料は、名古屋大学大学院人文学研究科で開講されている言語統計処理a（春学期）で使用する資料です。私はこの講義を昨年2025度から担当しています（[2025年度の資料はこちら](https://masato-terai.github.io/stat_class_2025/)）。この講義資料の内容は予告なく更新される可能性があります。<br>
　この講義では、15回の講義終了時に，受講者が以下の知識・能力を身につけていることを目標としています。


1. 統計処理の手続きに関する知識

2. 分析結果を適切に解釈し、説明する能力

3. プログラム言語(R)を用いた統計処理能力

4. 統計理論の数学・概念的知識

<div class="alert alert-info">
  <strong>注</strong> 
  
- Rがインストールされているパソコンを毎回の講義で必ず持参してください。

- 講義内容、講義スケジュールは講義の進度等によって変更する可能性があります。

</div>

## 講義スケジュール
- Week 1：Rおよび開発環境のインストール、Quarto
- Week 2：要約統計量
- Week 3：推測統計学
- Week 4：統計的検定の論理と *t検定*
- Week 5：相関分析
- Week 6：単回帰分析
- Week 7：重回帰分析(1)：概要
- Week 8：重回帰分析(2)：コーディングの変更
- Week 9：重回帰分析(3)：交互作用の解釈
- Week 10：一般化線形モデル：ロジスティック回帰分析
- Week 11：階層モデル
- Week 12：効果量と検定力分析
- Week 13：ノンパラメトリック検定
- Week 14：tidyverseパッケージによるデータの加工と可視化
- Week 15：言語研究とオープンサイエンス

## 講義資料
- [```https://github.com/masato-terai/statslec_quarto/```](https://github.com/masato-terai/statslec_quarto/)へアクセスすると、この講義資料のGitHubレポジトリにジャンプします。左上のGitHubのロゴをクリックしてもOKです。

- このレポジトリ全体のファイルをダウンロードすることも可能です。[<> Code]の下三角をクリックし、[Download ZIP]を選択してください。

- 特に重要なファイルは以下です。

  - ```.qmd```がそれぞれの章のソースコードです。

  - ```renv```フォルダは、パッケージの情報を格納しています。```renv::restore()```で寺井の環境を再現できます。詳しくは```renv```パッケージの説明をご覧ください。

  - ```sample_data```フォルダは、この講義で使用する模擬データを格納しています。講義中にここからダウンロードするように指示を出します。

## 成績評価について
- 小テスト（20%）、演習課題（40%）、レポート試験（40%）
  - 上記の各評価100点満点に換算し、それらを合計した得点が60点以上を合格とする。
  
  - A+（100-95）、A（94-80）、B（79-70）、C（69-65）、C-（64-60）、F（59-0）

## 質問に関して
- 学位論文やその他プロジェクトへの質問へは原則お答えしません。<u>回答する質問は本講義に関するものだけです。</u>

  - 共同研究者としてプロジェクトに加えてくださっている方々や、お金を払って相談を依頼してくださる方々がいます。

- 質問はTACT上でお願いします。1日経っても返信がない場合は、メールアドレスに連絡していただければ幸いです。